# .github/workflows/deploy.yml

name: Deploy Blog to Server # 工作流程的名称

on:
  push:
    branches:
      - main # 仅在推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 运行器

    steps:
      - name: Checkout repository # 第一步：检出代码
        uses: actions/checkout@v4 # 使用官方的 checkout action

      # 如果您的博客需要构建步骤，请在这里添加
      # 例如，使用 Hugo 构建：
      # - name: Setup Hugo
      #   uses: peaceiris/actions-hugo@v2
      #   with:
      #     hugo-version: 'latest'
      # - name: Build Hugo site
      #   run: hugo

      - name: Deploy to Server via SSH # 第二步：通过 SSH 部署
        uses: appleboy/ssh-action@master # 一个流行的 SSH action
        with:
          host: ${{ secrets.SERVER_HOST }}         # 服务器 IP 地址或域名
          username: ${{ secrets.SERVER_USERNAME }}   # 登录服务器的用户名
          key: ${{ secrets.DEPLOY_KEY }}          # 您刚刚添加的 SSH 私钥
          port: ${{ secrets.SERVER_PORT || 22 }}    # SSH 端口，默认为 22 (可选)
          script: | # 在服务器上执行的命令
            echo "Connected to server!"
            cd /opt/blog/  # 假设这是您博客在服务器上的目标路径
            ls -la
            echo "Deployment script finished."
            # 在这里添加您实际的部署命令，例如：
            # git pull # 如果服务器上也是一个 git 仓库
            # rsync -avz --delete public/ user@host:/var/www/html/ # 如果需要同步构建后的 public 目录
            # sudo systemctl restart nginx # 例如重启 Nginx