# .github/workflows/deploy.yml

name: Build and Deploy Blog

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- 构建步骤 (根据您的项目调整) ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build # 假设构建产物在 dist/

      # --- 部署步骤 ---
      - name: Deploy to Server via rsync
        uses: easingthemes/ssh-deploy@v5.0.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          ARGS: "-rlgoDzvc --delete --exclude='.git*'"
          SOURCE: "dist/"             # 【重要！】构建产物目录
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ secrets.TARGET_PATH }}  # <--- 在这里使用新的 Secret
          # SSH_PORT: ${{ secrets.SERVER_PORT || 22 }}

      # 如果您还需要使用 appleboy/ssh-action 执行一些部署后命令，也需要修改路径：
      - name: Post-deployment commands (Optional)
        if: always() # 确保即使部署失败也可能执行（或根据需要调整条件）
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            echo "Performing post-deployment tasks in ${{ secrets.TARGET_PATH }}"
            cd ${{ secrets.TARGET_PATH }}
            # 例如：
            # sudo systemctl restart nginx
            # pm2 reload my-app
            echo "Post-deployment tasks finished."